export default {
  GET_QUERY_SEARCH: "home/GET_QUERY_SEARCH",
  SET_QUERY_SEARCH: "home/SET_QUERY_SEARCH",

  FETCH_ITEM_LIST: "home/FETCH_ITEM_LIST",

  SET_ITEM_SELECTED: "home/SET_ITEM_SELECTED",
};
