export default {
  GET_QUERY_SEARCH: "home/GET_QUERY_SEARCH",
  SET_QUERY_SEARCH: "home/SET_QUERY_SEARCH",

  FETCH_ITEM_LIST: "home/FETCH_ITEM_LIST",

  FETCH_ITEM_DETAIL_SUCCESS: "home/FETCH_ITEM_DETAIL_SUCCESS",
  FETCH_ITEM_DETAIL_FAILURE: "home/FETCH_ITEM_DETAIL_FAILURE",
};
