export default {
  GET_QUERY_SEARCH: "home/GET_QUERY_SEARCH",
  SET_QUERY_SEARCH: "home/SET_QUERY_SEARCH",

  ITEM_LIST_FETCH: "home/ITEM_LIST_FETCH",
  ITEM_LIST_SUCCESS: "home/ITEM_LIST_SUCCESS",
  ITEM_LIST_FAILURE: "home/ITEM_LIST_FAILURE",
  ITEM_LIST_DENY: "home/ITEM_LIST_DENY",
};
